name: Build

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ["self-hosted", "Linux"]
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: thehanimo/pr-title-checker@7fbfe05602bdd86f926d3fb3bccb6f3aed43bc70 # v1.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/pr-title-checker-config.json"

  build:
    name: Build
    needs: validate-pr-title
    runs-on: ["self-hosted", "Linux"]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Install pre-commit
        run: python3 -m pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Install build dependencies
        run: sudo apt-get install -y gcc libsqlite3-dev

      - name: Build
        run: go build -v ./...
        env:
          CGO_ENABLED: "1"

      - name: Test
        run: go test ./...
        env:
          CGO_ENABLED: "1"
